# This function takes the removed_epochs.csv file generated by find_deleted_epochs.py to remove those same epochs from correct_raw_epochs.mat and generate a new file clean_raw_epochs.mat
# It does not generate epochs summary because it is the same as in Pre-processed
"""
Batch RAW Epoch Selection
This script is designed to automate the process of selecting epochs from RAW EEG data based on manual annotations of removed epochs. It performs the following steps:
1. Copies the `Removed_epochs.csv` file to the 3.RAW epochs directory for centralization.
2. Loads the `Removed_epochs.csv`, `Correct_labels.csv`, and `Correct_epochs.mat` files.
3. Identifies which epochs correspond to the removed annotations.
4. Removes the identified epochs from both the labels and the EEG data.
5. Saves the cleaned labels and epochs as `Clean_labels.csv` and `Clean_epochs.mat` respectively.
The script is structured to process multiple subjects and sessions, allowing for efficient batch processing of EEG data. It also includes error handling to skip specific subjects or sessions if needed.

Author:
Mario Lobo (UPM)
mario.lobo.alonso@alumnos.upm.es
Version:
16-04-2026

"""

import os
import shutil
import pandas as pd
import numpy as np
from scipy.io import loadmat, savemat


def delete_epochs(removed_epochs_path, removed_RAW_epochs_path, correct_RAW_labels_path, clean_RAW_labels_path, correct_RAW_epochs_path, clean_RAW_epochs_path):
    """
    Deletes epochs marked as noisy from the RAW data.

        Parameters:
        removed_epochs_path (str): Path to the CSV file containing the epochs marked for removal.
        removed_RAW_epochs_path (str): Path where the removed epochs CSV will be copied in the RAW epochs directory.
        correct_RAW_labels_path (str): Path to the CSV file containing the correct labels for the RAW epochs.
        clean_RAW_labels_path (str): Path where the cleaned labels CSV will be saved.
        correct_RAW_epochs_path (str): Path to the .mat file containing the correct RAW epochs.
        clean_RAW_epochs_path (str): Path where the cleaned RAW epochs .mat file will be
        saved.

        Returns:
        None: The function saves the cleaned labels and epochs to the specified paths.
    """
    # ==============================
    # 1. Load Files
    # ==============================

    # Copy the removed epochs CSV to the RAW epochs directory for centralization
    os.makedirs(os.path.dirname(removed_RAW_epochs_path), exist_ok=True)
    shutil.copy(removed_epochs_path, removed_RAW_epochs_path)

    removed = pd.read_csv(removed_RAW_epochs_path)
    labels = pd.read_csv(correct_RAW_labels_path)

    mat = loadmat(correct_RAW_epochs_path)

    epochs = mat["EEGData"]  # shape esperado: [channels, samples, trials]

    print("Shape original epochs:", epochs.shape)
    print("Número de labels:", len(labels))


    # ==============================
    # 2. Finde index to delete
    # ==============================

    key_cols = ["EventType", "EventPosition"]

    merged = labels.merge(
        removed,
        on=key_cols,
        how="left",
        indicator=True
    )

    # Index of rows that match removed
    indices_to_remove = merged.index[merged["_merge"] == "both"].tolist()

    print("Número de epochs a eliminar:", len(indices_to_remove))


    # ==============================
    # 3. Delete labels
    # ==============================

    clean_labels = labels.drop(index=indices_to_remove).reset_index(drop=True)


    # ==============================
    # 4. Delete trials in EEG
    # ==============================

    epochs_clean = np.delete(epochs, indices_to_remove, axis=2)

    print("Shape limpio:", epochs_clean.shape)
    print("Número de labels limpio:", len(clean_labels))


    # ==============================
    # 5. Save results
    # ==============================

    clean_labels.to_csv(clean_RAW_labels_path, index=False)

    savemat(
        clean_RAW_epochs_path,
        {"EEGData": epochs_clean}
    )



if __name__ == "__main__":
    # Example usage
    pre_processed_root = "C:/Users/user/Desktop/Mario Lobo/Silent Speech Data Amazon Non-Native/3. Pre-processed"
    RAW_epochs_root = "C:/Users/user/Desktop/Mario Lobo/Silent Speech Data Amazon Non-Native/3. RAW Epochs"

    n_subjects = 3
    n_sessions = 2

    not_process_subjects_and_sessions = [{"Subject_03", "Session_02"}] #List of subjects that will not be processed (for example, if they have corrupted data)

    #Go across all the subjects in the pre-processed folder to find the deleted epochs for each session
    for i in range(1,n_subjects+1):
        subject = f'Subject_{i:02d}'

        #Go across all the sessions for each subject
        for session in range(1, n_sessions+1):

            session_name = f'Session_{session:02d}'
            if {subject, session_name} in not_process_subjects_and_sessions:
                print(f"Skipping {subject} {session_name}. See documentation for issues.")
                continue
            
            removed_epochs_path = os.path.join(pre_processed_root, subject, session_name, 'Removed_epochs.csv')
            removed_RAW_epochs_path = os.path.join(RAW_epochs_root, subject, session_name, 'Removed_epochs.csv')
            correct_RAW_labels_path = os.path.join(RAW_epochs_root, subject, session_name, 'Correct_labels.csv')
            correct_RAW_epochs_path = os.path.join(RAW_epochs_root, subject, session_name, 'Correct_epochs.mat')
            clean_RAW_labels_path = os.path.join(RAW_epochs_root, subject, session_name, 'Clean_labels.csv')
            clean_RAW_epochs_path = os.path.join(RAW_epochs_root, subject, session_name, 'Clean_epochs.mat')



            delete_epochs(removed_epochs_path, removed_RAW_epochs_path, correct_RAW_labels_path, clean_RAW_labels_path, correct_RAW_epochs_path, clean_RAW_epochs_path)